project:
  type: website

website:
  title: "Predicting Psychiatric Disorders"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Model.qmd
      - Sources.qmd
      - Data.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




